export const actionTypes = {
  ADD_FIRST: "ADD_FIRST",
  ADD_TOP: "ADD_TOP",
  ADD_BOTTOM: "ADD_BOTTOM",
  ADD_LEFT: "ADD_LEFT",
  ADD_RIGHT: "ADD_RIGHT",
  SET_ELEMENT: "SET_ELEMENT",
  RESET_ELEMENT: "RESET_ELEMENT",
};
